---
# This Playbook would setup the homelab server

- hosts: homelab
  become: yes

  roles:
  # System setup
      - role: system
        tags:
            - system
      
      - role: docker
        tags:
            - docker
      
      - role: portainer
        tags:
            - portainer

      - role: containers
        tags:
            - containers