---
# This Playbook will set up the homelab servers

- name: Defining the hosts from the inventory
  hosts: homelab
  become: true

  roles:
  # System setup
      - role: system
        tags:
            - system

      - role: docker
        tags:
            - docker

      - role: portainer
        tags:
            - portainer

      - role: containers
        tags:
            - containers
