---
- name: Check if wifi device exists and exit if not
  command: /usr/bin/nmcli device status | grep wifi
  register: result
  failed_when: '"wifi" not in result.stdout'
  changed_when: false

- name: Enable wifi connection
  command: /usr/bin/nmcli radio wifi on
  register: result
  failed_when: '"Error" in result.stdout'
  changed_when: false

- name: Connect to wifi
  command: /usr/bin/nmcli dev wifi connect {{ wifi_ssid }} password {{ wifi_password }}
  failed_when: '"Error" in result.stdout'
  changed_when: false
