---

- name: Remove potential duplicates of PermitRootLogin
  replace:
        dest: /etc/ssh/sshd_config
        after: 'PermitRootLogin'
        regexp: '^(.*)PermitRootLogin(.*)$'
        replace: ''

- name: Remove potential duplicates of PasswordAuthentication
  replace:
        dest: /etc/ssh/sshd_config
        after: 'PasswordAuthentication'
        regexp: '^(.*)PasswordAuthentication(.*)$'
        replace: ''

- name: Disable Root Login
  lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^(.*)PermitRootLogin'
        line: "PermitRootLogin without-password"
        state: present
        backup: true
  notify:
        - restart ssh

- name: Disable password authentication
  lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^(.*)PasswordAuthentication'
        line: "PasswordAuthentication no"
        state: present
        backup: true
  notify:
        - restart ssh
