---
- name: Clean up tasks
  include_tasks: clean-up.yaml

- name: Install Portainer
  include_tasks: install.yaml

- name: Setup admin
  include_tasks: admin.yaml
  when: admin_user and admin_password is defined

- name: Generate authentication token
  uri:
    url: "{{ portainer_endpoint }}/auth"
    method: POST
    return_content: true
    body_format: json
    body: '{"Username": "{{ admin_user }}", "Password": "{{ admin_password }}"}'
  register: auth_token
  when: admin_user and admin_password is defined

- name: Setup application endpoints
  include_tasks: endpoints.yaml
  when: endpoints is not none

- name: Configure Portainer settings
  include_tasks: settings.yaml
  when: configure_settings

- name: Configure Registry
  include_tasks: registry.yaml
  when: configure_registry
