---
- name: Ensure folder exists
  stat:
    path: "{{ docker_dir }}/homeassistant/"

- name: Copy the compose file
  template:
    src: templates/homeassistant.yaml
    dest: "{{ docker_dir }}/homeassistant/compose.yaml"
    mode: 0755

- name: Docker-compose up
  community.docker.docker_compose:
    project_src: "{{ docker_dir }}/homeassistant/"
