---
- name: Ensure folder exists
  file: path={{ docker_dir }}/homeassistant/ state=directory

- name: Copy the compose file
  template: 
    src: templates/homeassistant.yaml
    dest: "{{ docker_dir }}/homeassistant/compose.yaml"

- name: Docker-compose up
  community.docker.docker_compose:
    project_src: "{{ docker_dir }}/homeassistant/"