version: '3.6'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - homelab
    restart: always
    user: '1000'
    environment:
      - GF_INSTALL_PLUGINS=
    ports:
      - '3000:3000'
    volumes:
      - "{{ docker_dir }}/grafana/data:/var/lib/grafana"
      - "{{ docker_dir }}/grafana/config:/etc/grafana"

networks:
  homelab:
    external: true
