services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    networks:
      - homelab
    ports:
      - "8123:8123"
    # volumes:
      # - "{{ docker_dir }}/homeassistant:/config"
    environment:
      - TZ={{ timezone }}
    restart: always

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    networks:
      - homelab
    # volumes:
      # - "{{ docker_dir }}/mosquitto:/mosquitto"
    restart: always

networks:
  homelab:
    external: true
