version: '3.6'
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    networks:
      - homelab
    ports:
      - "8123:8123"
    volumes:
      - /run/dbus:/run/dbus:ro
      - "{{ docker_dir }}/homeassistant/config:/config"
    environment:
      - TZ={{ timezone }}
    restart: always
    privileged: true

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    networks:
      - homelab
    volumes:
       - "{{ docker_dir }}/mosquitto:/mosquitto"
    restart: always

networks:
  homelab:
    external: true
